import { useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

type DefaultLayoutProps = {
  children: React.ReactNode;
};

export default function DefaultLayout({ children }: DefaultLayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="default-layout">
        <div>{children}</div>
      </div>
    </>
  );
}
